INSERT into bot_step (step, substep, description) VALUES (1,0,"Сбор информации о пользователе");
INSERT into bot_step (step, substep, description) VALUES (1,1,"Получение фамилии");
INSERT into bot_step (step, substep, description) VALUES (1,2,"Получение имени");
INSERT into bot_step (step, substep, description) VALUES (1,3,"Получение Отчества");
INSERT into bot_step (step, substep, description) VALUES (1,4,"Получение фамилии");
INSERT into bot_step (step, substep, description) VALUES (1,5,"Получение информации о компании");
INSERT into bot_step (step, substep, description) VALUES (1,6,"Получение информации о должности");
INSERT into bot_step (step, substep, description) VALUES (1,7,"Получение информации о телефоне");
INSERT into bot_step (step, substep, description) VALUES (1,8,"Получение информации о email");
INSERT into bot_step (step, substep, description) VALUES (2,0,"Тестирование");